### ISSUE TITLE
[Expert] Easy way to get slime boots

### ISSUE THREAD

**Issue by FallenEagle1** [whatthedrunk/allthemods#380] opened 2017-01-14 17:13 UTC
Version: Expert .19

This isn't a huge problem, but there is an easy way to get slime boots early on. In tinkers there are a couple variants of them now, one for each slime type: green, purple, and blue.

Green has been changed to require slime crystals, in the spirit of making recipes more difficult, but the other two slime variants are still the default recipe. This allows players to get the boots faster than what seems to be planned. Like I said, not a huge issue, but figured I'd still point it out.

**Comment by al132** [comment] 2017-01-17 05:30
Duplicate of #375 this will be fixed in the next update

**Closed by al132** 2017-01-17 05:30 UTC
