### ISSUE TITLE
Sever/Client configs don't match

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#110] opened 2016-08-13 00:19 UTC
Issue Description:Configs for client and server files are not exact. I playtest on a community server and do not have access to the server directly. After troubleshooting with a staff memeber we found that baggins and dark utilites had different server and client configs. replacing the configs with the server ones seemed to work.

What happens: missing block/item error when trying to connect

What you expected to happen: connect successfully

Version of All the Mods:1.11

Added mods (Optifine, Fastcraft, etc.):

1.optifine
2.fastcraft
3.
...

**Comment by Carrots4U** [comment] 2016-08-16 17:27
Duplicate of https://github.com/whatthedrunk/allthemods/issues/112 which is now fixed.

**Closed by Carrots4U** 2016-08-16 17:27 UTC
