### ISSUE TITLE
All the Sky - Report unobtainable items here

### ISSUE THREAD

**Issue by whatthedrunk** [whatthedrunk/allthemods#237] opened 2016-10-19 21:16 UTC
[Pack is located here if you want to help out with the super early build. ](https://minecraft.curseforge.com/projects/all-the-sky)
- [x] Osmium
- [x] Bee's 
- [ ] Apatite
- [ ] Rubber Tree sapling IC2
- [ ] Rubber Tree sapling TechReborn
- [ ] yellorium 

Things to add to oredict
- [ ] IC2 and Tech Reborn Sapplings
- [ ] IC2 Raw Carbon Fibre & Tech Reborn Carbon
- [ ] IC2 Raw Carbon Mesh & Tech Carbon Mesh
- [ ] IC2 and Tech Reborn Carbon Plate

**Comment by rgtexa** [comment] 2016-10-21 21:48
Unable to craft Actually Additions Dough - recipe conflicts with Ex Compressum Cow Bait.

**Comment by mjctechguy** [comment] 2016-10-22 03:49
Apatite

**Comment by stripeyhorse** [comment] 2016-10-23 08:28
Osmium can be fixed with the Ex Nihilo Config.

B:"force osmium"=true

**Comment by stripeyhorse** [comment] 2016-10-23 10:08
yellorium is unavailable.

**Comment by stripeyhorse** [comment] 2016-10-23 11:57
Actually Additions Dough is craftable. use the button in the crafting table to switch between recipes,

CONFIRMED working.

**Comment by Oli4TheWin** [comment] 2016-11-02 07:40
pestle and mortar isnt craftablr right?

**Comment by OrdinatorStouff** [comment] 2017-03-20 14:10
closing due to mostly no longer being relevant

**Closed by OrdinatorStouff** 2017-03-20 14:10 UTC
Labels: A.T.S.
