### ISSUE TITLE
ConcurrentModificationException crash on taking nether portal back to overworld

### ISSUE THREAD

**Issue by tivec** [whatthedrunk/allthemods#113] opened 2016-08-15 10:38 UTC
Issue Description:

I get a ConcurrentModificationException crash when going through my nether portal back to my world. After reloading the game, I am situated at spawn, not near where I crashed, sometimes I spawn below ground.

What happens: Game crashes.  http://upaste.me/e6f030680e40c3aa6

What you expected to happen: Zone back to overworld.

Steps to reproduce:

Unfortunately, I haven't had a chance to reproduce this in another world yet.

Version of All the Mods: v1.11

Added mods (Optifine, Fastcraft, etc.):

1. Optifine added, but crash happens without.

**Comment by DietmarKrause** [comment] 2016-08-16 05:46
perhaps a duplicate of my issue here: https://github.com/whatthedrunk/allthemods/issues/95
In my case i get a crash on every case of returning to the overwold. In a fresh new world i build a nether portal in creative right at the start only to see if it works. So it does. The issue is reportet at several mods as an issue (mekanism and journey map) .

**Comment by Carrots4U** [comment] 2016-08-16 17:22
Issue is already reported here,https://github.com/whatthedrunk/allthemods/issues/95. Please see here for further troubleshooting :smile:

**Closed by Carrots4U** 2016-08-16 17:22 UTC
