### ISSUE TITLE
Inventory Issues

### ISSUE THREAD

**Issue by jezzen** [whatthedrunk/allthemods#312] opened 2016-12-05 04:01 UTC
Issue Description:
In the latest version, I've been having many issues with inventory management which are extremely annoying. I'm not sure if something was added or updated in the current version that caused this or what.

What happens:
Several of the inventory management mods aren't working correctly.

Sorting from inventory tweaks often fails leaving items unsorted, picked up, or in other opened inventories (i.e. trying to sort a chest sometimes sends items to your inventory). It seems to work most of the time when only 'simple' items are in the inventory.

Item scroller fails in many cases where scrolling up on most stacked items ends up picking them up.

Right clicking a crafting grid output (at least for the vanilla 2x2 and 3x3, not sure of others) crafts once on the first click and the remainder on the second instead of the usual craft a whole stack.

Shift + control + clicking would be unsuccessful at moving items between inventories.

W + clicking would pick up the item instead of sending it to the crafting grid. Trying again when the item is held does it successfully.

Possibly connected to the previous, shift left-clicking causes a short visual glitch where one crafting result is in its own stack separate from the rest of the crafted items before going to the correct places.

There was one instance, where I couldn't combine 2 stacks of flint, though possibly unconnected. One had been in the enderIO SAG mill, but the actually additions information would not show up so I could not check 

What you expected to happen:
All of the above actions working as they previously did.
Some items seem to work correctly. My stone sharpening kits from tinkers seem immune to the issue.

Steps to reproduce:
Try any of the mentioned actions, or maybe even ones that I did not think of.

Version of All the Mods: ATM 1.49

Added mods (Optifine, Fastcraft, etc.):
I've played around with adding/removing optifine, fastcraft, and foamfix (foamfix didn't work too well in the previous ATM version where I added it alongside optifine and fastcraft) but the problem persisted with or without the changes.

Sorry for the rant, but this is just too annoying.

**Comment by jezzen** [comment] 2016-12-05 06:06
Just did a clean install. The W + click move to crafting grid looks fixed, and inventory tweaks sorting is a little better. The control + shift + click is looking alright too. As I said above, the only thing I changed was playing around with optifine, fastcraft and foamfix, so not sure what is happening there.

**Comment by DietmarKrause** [comment] 2016-12-08 06:46
can confirm. there is an issue. I have seen it with stone torches which do not mix up with the same item mounted /constructed weeks ago. This changes if you put them in the AE2 system and back. sme with other items.

**Comment by DietmarKrause** [comment] 2016-12-09 07:19
i have tested a few things. I see this issue always with arrows. dropped arrows from mobs dont mix up any more with self made one. You can work around this by putting both in the AE2 system, they stack then and you can grab them out as a stack. same with torches (at least stone torches) older one in my mine do not satck with new.

**Comment by PotDucky** [comment] 2017-03-22 20:46
unable to reproduce, Assume this was fixed in an earlier version. Reopen if you're still having issues.

**Closed by PotDucky** 2017-03-22 20:46 UTC
