### ISSUE TITLE
All The Sky - Wood Chippings going negative in my hotbar?

### ISSUE THREAD

**Issue by Twonz** [whatthedrunk/allthemods#249] opened 2016-10-26 03:13 UTC
Issue Description: I was throwing wood chippings into my barrel to make dirt and when i got to the end of the stack it let me keep adding, while showing a negative number on my item count.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Free dirt?

What you expected to happen: Limited dirt

Steps to reproduce:

1.Collect wood chippings
2.Manually put in oak barrel with an amount less than needed to fill up
3.Watch it go negative and stay on your hotbar until you try and interact with it
...

Version of All the Mods: All The Sky v 0.04

Added mods (Optifine, Fastcraft, etc.): n/a

1.
2.
3.
...

**Comment by Twonz** [comment] 2016-10-26 17:11
The wood chipping have to be in the last slot on your hotbar.

**Comment by OrdinatorStouff** [comment] 2016-12-26 17:45
As of ATS v1.0.1 I am unable to reproduce this. I'm assume it's been fixed in a release of Ex Nihilo since having been reported.

**Closed** 2017-03-20 14:15 UTC
Labels: A.T.S.
