### ISSUE TITLE
[1.10.2] Won't start minecraft 

### ISSUE THREAD

**Issue by kenturkey** [whatthedrunk/allthemods#21] opened 2016-07-07 00:19 UTC
![capture](https://cloud.githubusercontent.com/assets/20328578/16638655/eb3a3b80-43b6-11e6-81cb-0f56b5fa4bdc.PNG)

I press play and the launcher closes then brings me back to this after a sec...help??

**Comment by whatthedrunk** [comment] 2016-07-07 00:28
Uninstall your Java as its really old and install it again. I think the version I am using is 92 and that one is showing 25.

**Comment by kenturkey** [comment] 2016-07-07 00:43
I uninstalled and reinstalled but it still showing the same thing. It says i have java 8 update 91. I've played other mod packs that i've dowloaded from curse if that helps.

**Comment by whatthedrunk** [comment] 2016-07-07 00:47
There is a new version up that was just pushed, can you let me know if that works? If not I will need the full crash log to read over.

**Comment by kenturkey** [comment] 2016-07-07 21:28
So I played around with the java and such but nothing worked. I went to get the crash log but I'm not seeing it anywhere, maybe I'm looking in the right place?

**Comment by whatthedrunk** [comment] 2016-07-07 21:31
right click the all the mods icon in the launcher and click on "Open Folder" in there you will see Crash Logs, if there is no crash then give me the latest file in the logs folder.

**Comment by kenturkey** [comment] 2016-07-07 21:49
![latest log](https://cloud.githubusercontent.com/assets/20328578/16671000/0c9e810a-446b-11e6-8369-cdac26c7c25f.PNG)

**Comment by whatthedrunk** [comment] 2016-07-07 21:54
It looks like you are still uring Jave 1.8 build 25, want to make sure its uninstalled fully before you install [version 92 here](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html). After that try reinstalling the pack and making sure you are giving it more then 2gbs of ram.

**Comment by Carrots4U** [comment] 2016-07-08 23:23
Issue is identified and confirmed, so I'm closing the issue. If it is not resolved by updating java to the latest, reopen.

**Closed by Carrots4U** 2016-07-08 23:23 UTC
Labels: Java Issue
