### ISSUE TITLE
[1.10 v.1.13] Crash to Desktop while leaving Nether - Bioms o Plenty bug

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#126] opened 2016-08-18 19:33 UTC
Issue Description:another Crash while leaving the nether with the portal, this time a differentcrash report, something with bioms oplenty http://pastebin.com/zaz1yHQG
The Nether portal is at main Spawn point of the world

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
shutting internal server down. Crash to desktop,. After reloading the world i found myself in the water 200 block away but nothing lost of the inventory. Retried, but this time everything was fine. Not repeatable until now. It seems to be a diffent crash log as my other bug report. Therefore a new issue (?) 
What you expected to happen:
leave the Nether wihout crash
Steps to reproduce:

1.go to nether
2.leave nether
3.
...

Version of All the Mods: 1.13

Added mods (Optifine, Fastcraft, etc.):

1.nothing added
2.
3.
...

**Comment by whatthedrunk** [comment] 2016-08-19 18:18
Does this still happen in 13c?

**Comment by DietmarKrause** [comment] 2016-08-20 10:06
I have tried it twice. The change from Nether to Overworld seems to be FAR faster than before and 2 times evrything was fine. No crash of this kind (but still a crash in my second world with the other issue reportet elsewhere). What has changed?  Config changes?

**Comment by DietmarKrause** [comment] 2016-08-25 06:05
until now no forther Crash relating to BOB in this world. (But the other crash in old World reported elesewhere is still there). Issue can be closed from my end.

**Comment by DietmarKrause** [comment] 2016-08-25 20:38
with latest Update 1.16 b got this cash http://pastebin.com/7mtDQt2u BOP already. It ruines nerves :(. That means the problem is not solved

**Comment by Carrots4U** [comment] 2016-09-03 18:27
Duplicate of https://github.com/whatthedrunk/allthemods/issues/95

**Closed by Carrots4U** 2016-09-03 18:27 UTC
Labels: Major Bug
