### ISSUE TITLE
NPE Crash From Rough Mobs/EnderIO Interaction

### ISSUE THREAD

**Issue by EdgarAllen** [whatthedrunk/allthemods#41] opened 2016-07-14 00:39 UTC
Rough Mobs do not like to be attacked by an EnderIO Killer Joe. Causes NPE crash. 

http://pastebin.com/EWd5dxSx

**Comment by Carrots4U** [comment] 2016-07-14 02:09
It's caused by Rough Mobs Endermen, it's already fixed in the next update.

**Closed by Carrots4U** 2016-07-14 02:09 UTC
