### ISSUE TITLE
Server restart prompt y/n is reversed

### ISSUE THREAD

**Issue by Ricket** [whatthedrunk/allthemods#466] opened 2017-04-16 18:35 UTC
When prompted "Restart now (y) or exit to shell (n)?", I type "n" to exit to shell. The server instead restarts.

From ServerStart.sh:

        echo "Server will restart in ~10 seconds. No input needed..."
        read -t 12 -p "Restart now (y) or exit to shell (n)?  " answer
        if [[ "$answer" =~ ^([yY][eE][sS]|[yY])+$ ]]; then
                echo "INFO: User cancelled restart; exiting to shell" >>serverstart.log 2>&1
                exit 0
        fi

It is checking for "y" or "yes" to exit. But the text of the prompt said that "n" means exit to shell.

The Version of All the Mods: 2.54b

**Comment by OrdinatorStouff** [comment] 2017-04-17 01:17
This has already been fixed in our dev branch it's just taken me a long time to finish the windows version so we can release them at the same time. I'll close this one since it's a duplicate of #420 but I really really appreciate you taking the time to make the report and give us feedback, so thank you!

Future reports can go to https://github.com/AllTheMods/Server-Scripts as well since we're slowly phasing out this repo I think.

**Closed by OrdinatorStouff** 2017-04-17 01:17 UTC
